{% set name = "unstructured-client" %}
{% set version = "0.25.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: adb97ea56ce65f8b277d5b05f093e9d13a3320ac8dea7265ffa71f5e13ed5f84
    patches:
      - patches/0001-fix-python-38.patch  # [py==38]
  - url: https://raw.githubusercontent.com/Unstructured-IO/unstructured-python-client/v{{ version }}/_test_unstructured_client/unit/test_split_pdf_hook.py
    sha256: 1026e9fd784287e9d0a395d2f82ff856d4523a016da26be04bf473e0b9ff45b0
  - url: https://github.com/Unstructured-IO/unstructured-python-client/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8be7c5b83baae8c61b9ff389f02f4123a6558047c6fbefd6b3f38f850486d032
    folder: gh_src
    patches:
      - patches/0001-fix-test-module-path.patch
      - patches/0002-fix-test-for-py38.patch  # [py==38]

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - httpx >=0.27.0
    - nest-asyncio >=1.6.0
    - requests-toolbelt >=1.0.0
    - certifi >=2023.7.22
    - charset-normalizer >=3.2.0
    - dataclasses-json >=0.6.4
    - deepdiff >=6.0
    - idna >=3.4
    - jsonpath-python >=1.0.6
    - marshmallow >=3.19.0
    - mypy_extensions >=1.0.0
    - packaging >=23.1
    - pypdf >=4.0
    - python-dateutil >=2.8.2
    - requests >=2.31.0
    - six >=1.16.0
    - typing_inspect >=0.9.0
    - typing-extensions >=4.7.1
    - urllib3 >=1.26.18

test:
  imports:
    - unstructured_client
  source_files:
    - gh_src/_test_unstructured_client
    - gh_src/_sample_docs/*
    - gh_src/README.md
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-mock
    # requests-mock not available for py312
    - requests-mock  # [py<312]
    - requests-toolbelt
    # not used by the unit tests
    # - pypdf
    # - deepdiff
    # - uvloop
  commands:
    - pip check
    - cd gh_src/
    - pytest _test_unstructured_client/unit -v  # [py<312]
    - pytest _test_unstructured_client/unit/test_split_pdf_hook.py -v  # [py>=312]

about:
  home: https://github.com/Unstructured-IO/unstructured-python-client
  license: MIT
  license_file: LICENSE.md
  license_family: MIT
  summary: Python Client SDK for Unstructured API
  description: |
    Unstructured provides a platform and tools to ingest and process
    unstructured documents for Retrieval Augmented Generation (RAG)
    and model fine-tuning.
  doc_url: https://docs.unstructured.io/welcome
  dev_url: https://github.com/Unstructured-IO/unstructured-python-client

extra:
  recipe-maintainers:
    - jan-janssen
